server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fraud
    username: junive
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true