services:
  mysql:
    image: "mysql:8.0.28"
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=junive
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=customer
    ports:
      - "3306:3306"
    expose:
      - 3306


customer:
  image: junive/customer:latest
  container_name: customer
  ports:
    - "8080:8080"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  networks:
    - spring
    - mysql
  depends_on:
    - mysql

networks:
  mysql:
    driver: bridge

volumes:
  mysql: